= Generic file management tools for fast sorting, filtering, tagging documents
(C) 2023 Yury Benesh

== Overview
Distributed under GPLv3+ without any warranty, see link:../COPYING[].

A plain-text based toolset to collect files into lists, lists with tags,
filter by saved filters, sort by saved sort profiles, iteratively label,
preview, and process. Generated metadata is meant to be easily passed to other
programs for processing.

== Functions

* Build a plain text file containing a file list (one path by line).
* Build rich (TOML) format file lists to enable labeling files with metadata
(tags).
* Export rich file lists to plain ones to be used with other software/bash.
* Allow complex filter and sorting processing.
* Read saved file list and filter it out and sort with saved profiles.
* Operate on rich format file lists, filter by tags.
* Generate temporary symbolic links to browse selected lists with third-party
software.
* GUI with image previews to visually operate on lists.
* Associated files feature, e.g. assign tags to .xmp and .orf/.raw when tag is
assigned to jpeg.

== Use case for image processing
* Use 'fd -a' to build a plain text file list with absolute paths.
* Build a rich file list from it.
* Setup a filter to select only JPEGs
* Sort by date
* Iterate visually via GUI and attach tags to each file
* Filter the rich file list by tags, and produce symbolic links to browse with
favourite image viewer.
* Tag files to delete, generate such file list, export to plain text, rm for
each.

== Sample metadata file

[source,toml]
----
[[files]]
path="/mnt/asdasdsad/file.jpeg"
tags=["abc", "def", "aaa"]

[[files]]
path="/mnt/asdasdsad/other-file.jpeg"
tags=[]

[[files]]
path="/mnt/asdasdsad/notags-file.jpeg"

----

== Sample filter file/view file section

[source,toml]
----
# select files which do not have tags added to them yet
[[filters]]
filter = "Untagged"

# include = true is implicit, if you need to exclude matched files, set to false
[[filters]]
include = true

[filters.filter.AnyTagOf]
tags = ["tag1", "tag2"]

[[filters]]
include = false

[filters.filter.PathContains]
value = "myname"

# and from those select only from the specified day
[[filters]]
filter="date-is"
date=1979-05-27

# or from from the specified period
[[filters]]
filter="date-between"
start=1979-05-27
end=1979-05-28

# or from the specified day and later (the days after the specified day to now)
[[filters]]
filter="date-newer"
from=1979-05-27

# or from the specified day and earlier (the days preceeding the specified day)
[[filters]]
filter="date-older"
from=1979-05-27
----

== Sample groups file/view file section

[source,toml]
----

# 'suffix-groups' allow to join related files, and on GUI display only
# the first one based on their suffixes ('ends with'), and to perform
# operations on the group (i.e. delete, move, assign tags to every file
# of the group. If the first file is not found, group is discarded.
[[suffix-groups]]
suffixes = [".mov", ".mov.xmp"]
case-sensitive = false

[[suffix-groups]]
suffixes = [".jpg", ".jpg.xmp", ".orf", ".orf.xmp"]
case-sensitive = false

# In case there's no jpeg file with the same name:
[[suffix-groups]]
suffixes = [".orf", ".orf.xmp"]
case-sensitive = false

----

== Sample sorting file/view file section

[source,toml]
----
# sort by file name only
[[sorting]]
sort="base-name"

# sort by the full path string including the file name
[[sorting]]
sort="full-path"

# by file size, descending
[[sorting]]
sort="size-big-first"

[[sorting]]
sort="size-small-first"

[[sorting]]
sort="date-old-first"

[[sorting]]
sort="date-new-first"

----

== Metadata files in directories
A file "_tags.toml" contains the file list for only files in the same directory,
and paths are relative, i.e. contain only the file name itself.

.Commands to manage such files
* Create
* Remove non-existing files from list

